# @package _global_
module:
  _target_: emg2qwerty.lightning.TDSConvCTCModule
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [384] # 384, 480, 600
  block_channels: [24, 24, 24, 24]
  kernel_width: 32  # Total temporal receptive field of 125 samples given 4 layers
  #added parts
  hidden_size: 128
  num_layers: 3
  #droupout_rate: 0.3
  #gru_hidden: 128
  #gru_layers: 2

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
